services:
  chatbot:
    image: taegun1011/dabid_ai:1.1.4
    container_name: chatbot_server
    ports:
      - "8000:5000"
    depends_on:
      - redis
    environment:
      - OPENAI_API_KEY
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
    command: gunicorn -w 4 --threads 2 -b 0.0.0.0:5000 --chdir app app:app

  redis:
    image: redis
    container_name: chatbot_db
    ports:
      - "16379:16379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

