spring:
  application:
    name: dabid

  # Elasticsearch
  elasticsearch:
    rest:
      uris: http://elasticsearch:9200

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  # Scheduler ThreadCount
  quartz:
    properties:
      org.quartz.threadPool.threadCount: 20

  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://172.31.76.123:3306/dabid

    password: dabid
  # SQL Encoding
  sql:
    init:
      encoding: UTF-8
      mode: always

  #JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  #Security
  security:
    user:
      name: admin
      password: dabid
  #MongoDB
  data:
    mongodb:
      uri: mongodb://root:dabid@172.31.76.123:27017/dabid?authSource=admin

mybatis:
  mapper-locations: classpath:mapper/*.xml

jwt:
  key: /PrvvKm+CrnZUHBxKhqQNzhvN0QxnhGB1OzR1tV19yM=
  access:
    time: 10800
  refresh:
    time: 2592000

cloud:
  aws:
    credentials:
      access-key: AKIA6GBMGEM7RJN3IVWT
      secret-key: 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
    s3:
      bucket: dabid-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

server:
  servlet:
    encoding:
      enabled: 'true'

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: dabid

point:
  buy:
    deposit: 5000

