spring:
  # Elasticsearch
  elasticsearch:
    rest:
      uris: localhost:9200

  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dabid?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    password: dabid

  data:
    redis:
      host: localhost
      port: 6379
      password: dabid

    mongodb:
      uri: mongodb://localhost:dabid@mongodb:27017/dabid?authSource=admin

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: all
    consumer:
      group-id: dabid-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      enable-auto-commit: false
      max-poll-records: 500
      properties:
        spring:
          json:
            trusted:
              packages: "*"  # 신뢰할 패키지 (추후수정) "com.ssafy.dabid.domain.deal.entity"
      value-deserializer.delegate: org.springframework.kafka.support.serializer.JsonDeserializer  # JsonDeserializer 위임
    template:
      default-topic: dabid-topic