spring:
  application:
    name: dabid

  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dabid
    password: dabid
  # SQL Encoding
  sql:
    init:
      encoding: UTF-8
  #JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: 'true'

server:
  servlet:
    encoding:
      enabled: 'true'