spring:
  application:
    name: dabid

  # Scheduler ThreadCount
  quartz:
    properties:
      org.quartz.threadPool.threadCount: 20

  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dabid
    password: dabid
  # SQL Encoding
  sql:
    init:
      encoding: UTF-8
  #JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: 'true'

cloud:
  aws:
    credentials:
      access-key: AKIA6GBMGEM7RJN3IVWT
      secret-key: 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
    s3:
      bucket: dabid-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

server:
  servlet:
    encoding:
      enabled: 'true'

point:
  buy:
    deposit: 5000

